// Generated by gencpp from file multiple_machines/MotorsPwm.msg
// DO NOT EDIT!


#ifndef MULTIPLE_MACHINES_MESSAGE_MOTORSPWM_H
#define MULTIPLE_MACHINES_MESSAGE_MOTORSPWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiple_machines
{
template <class ContainerAllocator>
struct MotorsPwm_
{
  typedef MotorsPwm_<ContainerAllocator> Type;

  MotorsPwm_()
    : left_motor_pwm(0)
    , right_motor_pwm(0)  {
    }
  MotorsPwm_(const ContainerAllocator& _alloc)
    : left_motor_pwm(0)
    , right_motor_pwm(0)  {
  (void)_alloc;
    }



   typedef uint32_t _left_motor_pwm_type;
  _left_motor_pwm_type left_motor_pwm;

   typedef uint32_t _right_motor_pwm_type;
  _right_motor_pwm_type right_motor_pwm;





  typedef boost::shared_ptr< ::multiple_machines::MotorsPwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiple_machines::MotorsPwm_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsPwm_

typedef ::multiple_machines::MotorsPwm_<std::allocator<void> > MotorsPwm;

typedef boost::shared_ptr< ::multiple_machines::MotorsPwm > MotorsPwmPtr;
typedef boost::shared_ptr< ::multiple_machines::MotorsPwm const> MotorsPwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiple_machines::MotorsPwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiple_machines::MotorsPwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multiple_machines

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'multiple_machines': ['/home/grzesiek/ros-inz/tutorial-1/catkin_ws/src/multiple_machines/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiple_machines::MotorsPwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_machines::MotorsPwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_machines::MotorsPwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cae0766230de6a370bc83970582495e0";
  }

  static const char* value(const ::multiple_machines::MotorsPwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcae0766230de6a37ULL;
  static const uint64_t static_value2 = 0x0bc83970582495e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiple_machines/MotorsPwm";
  }

  static const char* value(const ::multiple_machines::MotorsPwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 left_motor_pwm\n\
uint32 right_motor_pwm\n\
";
  }

  static const char* value(const ::multiple_machines::MotorsPwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor_pwm);
      stream.next(m.right_motor_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorsPwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiple_machines::MotorsPwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiple_machines::MotorsPwm_<ContainerAllocator>& v)
  {
    s << indent << "left_motor_pwm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left_motor_pwm);
    s << indent << "right_motor_pwm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right_motor_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLE_MACHINES_MESSAGE_MOTORSPWM_H
