// Generated by gencpp from file multiple_machines/ProtocolMessage.msg
// DO NOT EDIT!


#ifndef MULTIPLE_MACHINES_MESSAGE_PROTOCOLMESSAGE_H
#define MULTIPLE_MACHINES_MESSAGE_PROTOCOLMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiple_machines
{
template <class ContainerAllocator>
struct ProtocolMessage_
{
  typedef ProtocolMessage_<ContainerAllocator> Type;

  ProtocolMessage_()
    : flag()
    , value(0)  {
    }
  ProtocolMessage_(const ContainerAllocator& _alloc)
    : flag(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flag_type;
  _flag_type flag;

   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::multiple_machines::ProtocolMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiple_machines::ProtocolMessage_<ContainerAllocator> const> ConstPtr;

}; // struct ProtocolMessage_

typedef ::multiple_machines::ProtocolMessage_<std::allocator<void> > ProtocolMessage;

typedef boost::shared_ptr< ::multiple_machines::ProtocolMessage > ProtocolMessagePtr;
typedef boost::shared_ptr< ::multiple_machines::ProtocolMessage const> ProtocolMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiple_machines::ProtocolMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multiple_machines

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'multiple_machines': ['/home/grzesiek/ros-inz/tutorial-1/catkin_ws/src/multiple_machines/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiple_machines::ProtocolMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_machines::ProtocolMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_machines::ProtocolMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b6905edf78d9494d3df19c48997fa57";
  }

  static const char* value(const ::multiple_machines::ProtocolMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b6905edf78d9494ULL;
  static const uint64_t static_value2 = 0xd3df19c48997fa57ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiple_machines/ProtocolMessage";
  }

  static const char* value(const ::multiple_machines::ProtocolMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string flag\n\
uint32 value\n\
";
  }

  static const char* value(const ::multiple_machines::ProtocolMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProtocolMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiple_machines::ProtocolMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiple_machines::ProtocolMessage_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flag);
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLE_MACHINES_MESSAGE_PROTOCOLMESSAGE_H
